env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides:
  - files:
      - '*.js'
    rules:
      # JavaScript に限り `require` 構文を許容する。既定では全面禁止。
      # JavaScript は各種設定ファイルなど、トランスパイルの範囲外で使用する
      # 状況が多く、import が使いづらい。
      '@typescript-eslint/no-var-requires': 'off'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  project: ./tsconfig.json
root: true
rules:
  # 特定のファイルを除き、devDependencies に対する依存は禁止。
  # 既定では全面禁止。内部的に Webpack により Tree Shaking されるため、
  # 厳格な依存パッケージの分離を行う必要性は薄いが、整理しやすくするために
  # 一部パッケージを devDependencies へと分離している。
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.config.{j,t}s'
        - '**/*.{spec,test}.{j,t}{s,sx}'
  # import 構文における、順序の任意並び替えを警告付きで許可する。
  # 既定は無条件許可。import 部の雪だるま式肥大化問題対処のため導入。
  import/order: warn
  # prop-types の記述省略を許可する。既定は禁止。
  # トランスパイル済みコンポーネントを TypeScript ではないプロジェクトから
  # 再利用するようなシチュエーションでは必須だが、状況的に考えにくい。
  react/prop-types: 'off'
  # React 17 から、JSX/TSX における `React` のインポートは強制ではなくなり、
  # このルールも不要となった。既定は JSX/TSX において強制。
  # See: https://ja.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
  react/jsx-uses-react: 'off'
  # React 17 から、JSX/TSX における `React` のインポートは強制ではなくなり、
  # このルールも不要となった。既定は JSX/TSX において強制。
  # See: https://ja.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
  react/react-in-jsx-scope: 'off'
  # import 構文の複数 export における順序の任意並び替えを、警告付きで
  # 許可する。既定は無条件許可。import 部の雪だるま式肥大化問題対処のため。
  sort-imports:
    - warn
    # `import/order` ルールを優先し、矛盾しうるルールは無効化する。
    - ignoreCase: true
      ignoreDeclarationSort: true
