#!/bin/sh
# vim: set ft=sh:

set -eu

/Applications/Firefox.app/Contents/MacOS/firefox -new-window https://www.mozilla.org/ &
CERT=.cert
sudo mkcert -install
mkdir -p ${CERT}
sudo mkcert -cert-file ${CERT}/localhost.crt -key-file ${CERT}/localhost.key localhost
